# Homebrew configuration
export HOMEBREW_PREFIX="~/usr/local"
export HOMEBREW_CASK_OPTS="--appdir=${HOME}/Applications"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1
export PATH="${HOME}/bin":"${HOME}/.homebrew/bin":"${HOMEBREW_PREFIX}/bin":"${HOME}/.homebrew/opt/coreutils/libexec/gnubin":$PATH

# GPG Stuff
#export GPG_TTY="$(tty)"
#export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
#gpgconf --launch gpg-agent

# SOPS
export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt

# GO stuff
export GOPATH="${HOME}/.go"
export PATH="${PATH}":"${GOPATH}/bin"

# Sane Defaults
export EDITOR=$(brew --prefix)/bin/nvim

# ZINIT zsh plugin manager
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# starship prompt
#eval "$(starship init zsh)"
zinit ice from"gh-r" as"command" atload'eval "$(starship init zsh)"'
zinit load starship/starship

# zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light djui/alias-tips

# Add snippets
zinit snippet OMZP::git
zinit snippet OMZP::direnv
zinit snippet OMZP::sudo
zinit snippet OMZP::archlinux
zinit snippet OMZP::aws
zinit snippet OMZP::kubectl
zinit snippet OMZP::kubectx
zinit snippet OMZP::command-not-found
zinit snippet OMZP::fluxcd
zinit snippet OMZP::gpg-agent

# load completions
autoload -U compinit && compinit

zinit cdreplay -q

# Shell Integrations
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(brew shellenv)"


# Set emacs keybindings for the shell
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Aliases
alias ls='ls --color'

# source an extras.zsh for environment specific zsh integrations
if [ -f "${HOME}/.config/extras.zsh" ]; then . "${HOME}/.config/extras.zsh"; fi

# Podman Docker API compatibility
if command -v podman >/dev/null 2>&1; then
  podman_sock="$(podman machine inspect --format '{{ .ConnectionInfo.PodmanSocket.Path }}' 2>/dev/null)"
  if [[ -n "$podman_sock" ]]; then
    export DOCKER_HOST="unix://$podman_sock"
  fi
fi
